### ISSUE TITLE
Adicionar disqus aos posts

### ISSUE THREAD

**Issue by teles** [vivadecora/vivadecora.github.io#15]
Adicionar diqus aos posts para que eles possam ser comentados.
Verificar antes se já existe uma conta do vivadecora disponível para isso ou se é mais interessante criar uma conta somente para esse github.io.

**Comment by woliveiras** [comment]
Acho interessante criar um só pra esse blog pra quem segue o Viva Decora não receber alertas de engenharia.

**Comment by teles** [comment]
Boa, @woliveiras
