### ISSUE TITLE
Adicionar uma página de "trabalhe conosco"

### ISSUE THREAD

**Issue by teles** [vivadecora/vivadecora.github.io#2]
Acho uma boa ideia colocar uma página de trabalhe conosco, nem que seja no rodapé.
Colocar nessa página:
- Links para nossos 2 testes no github;
- Informação sobre "tem vaga ou não tem vaga hoje?"
- Espaço para se inscrever para saber quando teremos vaga;
- Explicação sobre o fato de que vamos analisar quaisquer PR nos repositórios independentemente da existência ou não de vagas;

cc @IuryAlves @taciogt @woliveiras

**Comment by woliveiras** [comment]
Essa parte: 

> Explicação sobre o fato de que vamos analisar quaisquer PR nos repositórios independentemente da existência ou não de vagas;

Creio que deva ficar nos repositórios dos testes.

**Comment by teles** [comment]
Pode ser @woliveiras
