### ISSUE TITLE
SEO para desenvolvedores front end.

### ISSUE THREAD

**Issue by teles** [vivadecora/vivadecora.github.io#8]
Pensei em escrever um texto sobre algumas técnicas e práticas de javascript, html e css que adotamos no Viva Decora.

Vou conversar sobre algumas dessas coisas com o Pedro e pensei em fazer uma lista que depois pode virar um post.

cc  @woliveiras  @taciogt @IuryAlves

**Comment by teles** [comment]
Lista preliminar:

* SPA podem ser indexadas usando prerender;
* Básico: minificação e concatenação de arquivos;
* Apenas um <h1> por página,
* Verifique sua estrutura de cabeçalhos com [web developer](http://chrispederick.com/work/web-developer/)
* URL amigável: prefira urls mais rasas, mantenha as palavras chaves a esquerda das url;
* Prepare seu site para ter css crítico e carregamento assíncrono; 
* Marcação semântica para elementos html com schema.org (Blog/Site); 
* Mantenha uma estrutura de títulos que seja fácil de trocar para validar hipóteses;
* Como fazer testes A/B para SEO
* Estrutura para imagens e vídeos

**Comment by teles** [comment]
* Mobile first no css, como fazer
* canonical, rel=prev, rel-next
* Sitemap html

**Comment by teles** [comment]
Links de ferramentas sobre o tema https://github.com/teles/awesome-seo

**Comment by woliveiras** [comment]
Mobile First no CSS da um artigo só sobre CSS, Media Queries e organização do CSS mano @teles 

Seria mais da hora. Da pra aprofundar bastante.

**Comment by teles** [comment]
Verdade, dá para fazer vários posts sobre os temas mencionados.

Agora pensei em fazer um post inicial, estilo lista do buzzfeed.

10 técnicas de front end para melhorar o SEO do seu site.
Com 10 itens assim:

Nome da técnica
[IMAGEM]
Descrição da técnica

@woliveiras

**Comment by woliveiras** [comment]
Interessante mano! 

A galera curte listas.

**Comment by teles** [comment]
cc @zapiano

**Comment by Zapiano** [comment]
@teles eu só vi isso agora (um pooouco atrasado xD) mas eu fiz um post (inaugural!) no meu blog sobre algumas das coisas que nós conversamos ai, pra organizar a ordem que eu vo colocar na casa nas proximas semanas: http://zapiano.com.br/frontend/front/licoes/2016/09/28/licoes-front-end.html

sobre esse post q vc disse q vcs vao fazer, voces tem um blog de dev do viva decora? la no pegcar a gte ta falando de criar um, talvez saia do mundo das ideias ainda esse ano.. ;)

**Comment by teles** [comment]
@Zapiano legal o post. 
Onde fica o repositório do seu blog? Pensei que ficasse no github mas não o encontrei rs.
